import * as THREE from "three";

const wood=new THREE.MeshStandardMaterial({color:0xb67b4d,roughness:.82});
const woodDark=new THREE.MeshStandardMaterial({color:0x765039,roughness:.95});
const soil=new THREE.MeshStandardMaterial({color:0x1c120d,roughness:1});
const soilRow=new THREE.MeshStandardMaterial({color:0x302017,roughness:1});
const stem=new THREE.MeshStandardMaterial({color:0x315d2d,roughness:.92});
const cane=new THREE.MeshStandardMaterial({color:0xb99760,roughness:.88});
const radishRed=new THREE.MeshStandardMaterial({color:0xc52842,roughness:.72});
const white=new THREE.MeshStandardMaterial({color:0xf3eee1,roughness:.75});
const leafMats=[0x1f5729,0x2f7133,0x43843d,0x5d9847,0x76a84f,0x8dbb58].map(color=>new THREE.MeshStandardMaterial({color,roughness:.8,side:THREE.DoubleSide}));
const loader=new THREE.TextureLoader();
const lettuceTexture=loader.load('/plant-icons/v2/lettuce.svg');lettuceTexture.colorSpace=THREE.SRGBColorSpace;
type InspectItem={title:string;subtitle?:string;lines:Array<{label:string;value:string}>};
function rng(seed:number){let v=seed>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/0x100000000;};}
function box(w:number,h:number,d:number,m:THREE.Material,x:number,y:number,z:number){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d,2,1,2),m.clone());q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;return q;}
function inspectable(root:THREE.Object3D,item:InspectItem){root.traverse(o=>{if(!o.userData.inspect){o.userData.inspect=item;o.userData.selectionRoot=root;}});}
function roundedLeaf(length:number,width:number,mat:number){const shape=new THREE.Shape();shape.moveTo(0,-length*.5);shape.bezierCurveTo(width*.75,-length*.28,width*.72,length*.22,0,length*.5);shape.bezierCurveTo(-width*.72,length*.22,-width*.75,-length*.28,0,-length*.5);const g=new THREE.ShapeGeometry(shape,3),q=new THREE.Mesh(g,leafMats[mat%leafMats.length].clone());q.geometry.rotateX(-Math.PI/2);q.castShadow=true;return q;}
function rosette(seed:number,size:number,layers:number){const r=rng(seed),g=new THREE.Group();for(let layer=0;layer<layers;layer++){const n=12-layer*2;for(let i=0;i<n;i++){const a=i/n*Math.PI*2+r()*.22,l=size*(.82-layer*.11)*(.9+r()*.2),q=roundedLeaf(l,size*.27*(.9+r()*.18),Math.floor(r()*leafMats.length));q.position.set(Math.cos(a)*size*(.26-layer*.045),size*(.10+layer*.07),Math.sin(a)*size*(.26-layer*.045));q.rotation.set(-.18-r()*.22,-a,(r()-.5)*.22);g.add(q);}}return g;}
function crossedArtwork(texture:THREE.Texture,size:number,height:number,seed:number,tint=0xffffff){const r=rng(seed),g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({map:texture,transparent:true,alphaTest:.18,side:THREE.DoubleSide,color:tint,depthWrite:true});for(let i=0;i<3;i++){const q=new THREE.Mesh(new THREE.PlaneGeometry(size,height),mat.clone());q.position.y=height*.46;q.rotation.y=i*Math.PI/3+r()*.16;g.add(q);}const top=new THREE.Mesh(new THREE.PlaneGeometry(size*.9,size*.9),mat.clone());top.position.y=height*.43;top.rotation.x=-Math.PI/2;top.rotation.z=r()*Math.PI;g.add(top);return g;}
function lettuce(seed:number){const r=rng(seed),g=crossedArtwork(lettuceTexture,.46,.38,seed,r()>.72?0xd8b6a2:0xffffff);g.scale.setScalar(.92+r()*.16);inspectable(g,{title:"Lettuce (mixed)",subtitle:"Textured production artwork",lines:[{label:"Spacing",value:"28 cm"}]});return g;}
function spinach(seed:number){const r=rng(seed),g=new THREE.Group();for(let cluster=0;cluster<3;cluster++){const p=rosette(seed+cluster*17,.28,3);p.position.set((r()-.5)*.11,0,(r()-.5)*.1);p.scale.set(.95+r()*.16,.75+r()*.12,.95+r()*.16);g.add(p);}inspectable(g,{title:"Spinach",subtitle:"Dense layered production foliage",lines:[{label:"Spacing",value:"20 cm"}]});return g;}
function carrot(seed:number){const r=rng(seed),g=new THREE.Group();for(let i=0;i<18;i++){const h=.22+r()*.17,q=roundedLeaf(h,.018+r()*.012,i),a=r()*Math.PI*2;q.position.set(Math.cos(a)*.045,.13+r()*.035,Math.sin(a)*.045);q.rotation.set(-.05-r()*.18,-a,(r()-.5)*.55);g.add(q);}inspectable(g,{title:"Carrot",lines:[{label:"Spacing",value:"7 cm"}]});return g;}
function radish(seed:number){const r=rng(seed),g=rosette(seed,.19,2),bulb=new THREE.Mesh(new THREE.SphereGeometry(.048,14,10),radishRed.clone());bulb.scale.set(1,.82,1);bulb.position.y=.025;g.add(bulb);g.scale.setScalar(.93+r()*.14);inspectable(g,{title:"Radish",lines:[{label:"Spacing",value:"8 cm"}]});return g;}
function onion(seed:number){const r=rng(seed),g=new THREE.Group();for(let i=0;i<6;i++){const h=.32+r()*.2,q=new THREE.Mesh(new THREE.CylinderGeometry(.004,.011,h,8),leafMats[i%4].clone());q.position.set((r()-.5)*.045,h/2,(r()-.5)*.045);q.rotation.z=(r()-.5)*.18;g.add(q);}inspectable(g,{title:"Spring onions",lines:[{label:"Spacing",value:"6 cm"}]});return g;}
function bean(seed:number){const r=rng(seed),g=new THREE.Group(),vine=new THREE.Mesh(new THREE.CylinderGeometry(.009,.014,1.52,8),stem.clone());vine.position.y=.76;g.add(vine);for(let i=0;i<24;i++){const a=i*1.23+r()*.5,q=roundedLeaf(.19+r()*.1,.07+r()*.025,i);q.position.set(Math.cos(a)*(.08+r()*.07),.14+i*.06,Math.sin(a)*(.07+r()*.03));q.rotation.set((r()-.5)*.35,-a,(r()-.5)*.3);g.add(q);if(i%7===0){const f=new THREE.Mesh(new THREE.SphereGeometry(.018,8,6),white.clone());f.position.copy(q.position);f.position.x+=.035;g.add(f);}}inspectable(g,{title:"Climbing beans",lines:[{label:"Spacing",value:"18 cm"},{label:"Support",value:"Bamboo trellis"}]});return g;}
function bambooTrellis(root:THREE.Group){const t=new THREE.Group(),z=-1.63;for(const x of[-.76,-.38,0,.38,.76])t.add(box(.026,1.78,.026,cane,x,.91,z));for(const y of[.65,1.12,1.62])t.add(box(1.78,.025,.025,cane,0,y,z));root.add(t);}
function rowMound(root:THREE.Group,z:number){root.add(box(1.68,.035,.34,soilRow,0,.305,z));}
function fullRow(root:THREE.Group,z:number,spacing:number,maker:(s:number)=>THREE.Group,seed:number,mobile:boolean){const width=1.64,effective=mobile?Math.max(spacing,.105):spacing,count=Math.floor(width/effective)+1,r=rng(seed*31);for(let i=0;i<count;i++){const p=maker(seed+i),x=count===1?0:-width/2+i*width/(count-1);p.position.set(x+(r()-.5)*.035,.32,z+(r()-.5)*.04);p.rotation.y+=(r()-.5)*.32;p.scale.multiplyScalar(.92+r()*.18);root.add(p);}}
function sign(root:THREE.Group,z:number,label:string){const g=new THREE.Group();g.add(box(.30,.11,.025,wood,.68,.48,z));g.add(box(.018,.24,.018,woodDark,.68,.35,z));g.userData.cropLabel=label;root.add(g);}
export function addDemonstrationBed3D(group:THREE.Group,mobile:boolean){const root=new THREE.Group(),width=2,depth=4,wall=.3,rail=.12;root.add(box(width-.18,.21,depth-.18,soil,0,.18,0));root.add(box(width+rail,wall,rail,wood,0,wall/2,-depth/2));root.add(box(width+rail,wall,rail,wood,0,wall/2,depth/2));root.add(box(rail,wall,depth,wood,-width/2,wall/2,0));root.add(box(rail,wall,depth,wood,width/2,wall/2,0));bambooTrellis(root);const rows:[number,number,(s:number)=>THREE.Group,number,string][]=[[-1.47,.18,bean,200,"BEANS (CLIMBING)"],[-.88,.28,lettuce,300,"LETTUCE (MIXED)"],[-.29,.08,radish,400,"RADISH"],[.30,.07,carrot,500,"CARROT"],[.89,.20,spinach,600,"SPINACH"],[1.48,.06,onion,700,"SPRING ONIONS"]];rows.forEach(([z,spacing,maker,seed,label])=>{rowMound(root,z);fullRow(root,z,spacing,maker,seed,mobile);sign(root,z,label);});inspectable(root,{title:"2 × 4 m demonstration bed",subtitle:"Textured foliage production benchmark",lines:[{label:"Size",value:"2.0 × 4.0 m"},{label:"Layout",value:"6 dense full crop rows"},{label:"Upgrade",value:"Textured lettuce + denser layered spinach"}]});group.add(root);return root;}
