import { expect, test, type Page } from "@playwright/test";
import * as THREE from "three";
import type { PlannerPlan } from "../../lib/garden/planner-plan";
import { gardenDimensions, resizeGarden } from "../../lib/garden/garden-dimensions";
import { addCropPoints, cropPlacementPoints, movePlanGroup, snapPlantingPoint, validateNewBuilding } from "../../lib/garden/garden-building";
import { areaPlants, bedRectangle, duplicatePlanSelection, movePlanSelection, reconcileOwnedPlants, rowPlants, validateEditorPlan } from "../../lib/garden/plan-editing";
import { generateSeasonalBedLayout } from "../../lib/garden/seasonal-bed-layout";
import { plantingSurfaces, structureSurface, surfaceContains, surfaceLocal } from "../../lib/garden/planting-surfaces";
import { surfaceWorld } from "../../lib/garden/planting-surfaces";
import { addRow } from "../../components/garden-object-renderers";

const fixture: PlannerPlan = { beds: [{ id: 1, name: "Salad bed", x: 10, y: 10, w: 25, h: 20 }], plantingAreas: [], rows: [],
  objects: [{ id: "raised", type: "structure", kind: "raised-bed-timber", x: 550, y: 550, widthCm: 240, depthCm: 160, heightCm: 60, rotationDeg: 30, label: "Raised bed" }] };
const liveKey = "blenheim-garden-live-plan";
const readPlan = (page: Page): Promise<PlannerPlan> => page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), liveKey);

test("resizing preserves physical geometry and rejects truncation", () => {
  const surface = plantingSurfaces(fixture)[0];
  const points = cropPlacementPoints(fixture, "Lettuce", surface, null, "fill", `object:${surface.id}`);
  const planted = addCropPoints(fixture, "Lettuce", "Butterhead", points, `object:${surface.id}`);
  const enlarged = resizeGarden(planted, 1800, 1600);
  validateEditorPlan(enlarged);
  expect(bedRectangle(enlarged.beds[0], enlarged)).toEqual(bedRectangle(fixture.beds[0], fixture));
  expect(rowPlants(enlarged.rows[0])).toEqual(rowPlants(planted.rows[0]));
  expect(gardenDimensions(enlarged)).toEqual({ width: 1800, height: 1600 });
  expect(() => resizeGarden(planted, 200, 200)).toThrow(/outside/);
  expect(() => resizeGarden(planted, NaN, 1000)).toThrow(/dimensions/);
  const plant = areaPlants({ ...enlarged, plantingAreas: [{ id: "a", bedId: 1, crop: "Lettuce", cropIcon: "L", variety: "Butterhead", spacingCm: 25, x: 0, y: 0, w: 100, h: 100, pattern: "single", count: 1, iconSize: 16, visualSpacing: "normal" }] }, { id: "a", bedId: 1, crop: "Lettuce", cropIcon: "L", variety: "Butterhead", spacingCm: 25, x: 0, y: 0, w: 100, h: 100, pattern: "single", count: 1, iconSize: 16, visualSpacing: "normal" });
  expect(plant[0].x).toBeGreaterThan(90);
});

test("rotated soil snapping, fill spacing, ownership, group moves and copies agree", () => {
  const object = fixture.objects[0]; if (object.type !== "structure") throw new Error("fixture");
  const surface = structureSurface(object), target = `object:${object.id}`;
  const snapped = snapPlantingPoint(fixture, { x: 563, y: 551 }, true, target), local = surfaceLocal(surface, snapped);
  expect(local.x / 10).toBeCloseTo(Math.round(local.x / 10));
  expect(local.y / 10).toBeCloseTo(Math.round(local.y / 10));
  const positions = cropPlacementPoints(fixture, "Lettuce", surface, null, "fill", target, 30);
  expect(positions.length).toBeGreaterThan(10);
  expect(positions.every((p) => surfaceContains(surface, p, 6))).toBe(true);
  const planted = addCropPoints(fixture, "Lettuce", "Butterhead", positions, target, 30);
  const group = movePlanGroup(planted, [{ kind: "object", id: object.id }, { kind: "row", id: planted.rows[0].id }], { x: 30, y: 20 });
  expect(rowPlants(group.rows[0])[0].x).toBeCloseTo(positions[0].x + 30);
  expect(rowPlants(group.rows[0])[0].y).toBeCloseTo(positions[0].y + 20);
  const copied = duplicatePlanSelection(planted, { kind: "object", id: object.id });
  expect(copied.rows.flatMap(rowPlants)).toHaveLength(positions.length * 2);
  validateEditorPlan(copied);
  const moved = movePlanSelection(JSON.parse(JSON.stringify(planted)), { kind: "object", id: object.id }, { x: 25, y: 35 });
  expect(moved.rows[0].surfaceId).toBe(target);
  expect(cropPlacementPoints(planted, "Lettuce", surface, null, "fill", target, 30)).toHaveLength(0);
  expect(() => validateNewBuilding(fixture, { ...fixture, objects: [...fixture.objects, { ...object, id: "overlap" }] })).toThrow(/overlaps/);
});

test("seasonal conditions and complete instanced rendering retain every plant", () => {
  const surface = plantingSurfaces(fixture)[0];
  const conditions = { ...fixture, bedProfiles: { [`${surface.kind}:${surface.id}`]: { sun: "partial" as const, soilDepthCm: 20, previousCrop: "Lettuce" } } };
  const seasonal = generateSeasonalBedLayout(conditions, surface, 9, "mixed");
  expect(seasonal.positions.every((p) => p.crop === "Herbs")).toBe(true);
  const row = { id: "dense", crop: "Lettuce", cropIcon: "L", variety: "Butterhead", spacingCm: 3, x1: 100, y1: 800, x2: 800, y2: 800, count: 201 };
  const root = new THREE.Group(); addRow(root, row, true, { ...fixture, rows: [row] });
  let proxies = 0, instances = 0;
  root.traverse((o) => { if (o.userData.plantProxy) proxies++; if (o instanceof THREE.InstancedMesh) { expect(o.count).toBe(201); instances++; } });
  expect(proxies).toBe(201); expect(instances).toBeGreaterThan(0);
  const desktop = new THREE.Group(); addRow(desktop, row, false, { ...fixture, rows: [row] });
  desktop.updateMatrixWorld(true);
  let lod: THREE.LOD | undefined;
  desktop.traverse((o) => { if (o instanceof THREE.LOD) lod = o; });
  expect(lod).toBeDefined();
  expect(lod!.position.x).toBeCloseTo(0);
  expect(lod!.position.z).toBeCloseTo(2.6);
  const camera = new THREE.PerspectiveCamera();
  camera.position.copy(lod!.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0, 3, 0)); camera.updateMatrixWorld();
  lod!.update(camera);
  expect(lod!.getCurrentLevel()).toBe(0);
  camera.position.y += 20; camera.updateMatrixWorld(); lod!.update(camera);
  expect(lod!.getCurrentLevel()).toBe(1);
});

test("owned plants follow 2D edits and bed copies without losing new rows", () => {
  const bed = plantingSurfaces(fixture).find((s) => s.kind === "bed")!;
  const row = { id: "owned", surfaceId: "bed:1", crop: "Lettuce", cropIcon: "L", variety: "Butterhead", spacingCm: 25,
    x1: bed.x, y1: bed.y, x2: bed.x, y2: bed.y, count: 1, placements: [{ id: "plant", x: 0, y: 0 }] };
  const original = { ...fixture, rows: [row] };
  const next = reconcileOwnedPlants(original, { ...original, beds: original.beds.map((b) => ({ ...b, x: b.x + 10, w: b.w * 2 })) });
  const from = bedRectangle(original.beds[0], original), to = bedRectangle(next.beds[0], next);
  expect(rowPlants(next.rows[0])[0].x).toBeCloseTo(to.x + (bed.x - from.x) * 2);
  const copied = duplicatePlanSelection(original, { kind: "bed", id: "1" });
  expect(copied.rows).toHaveLength(2);
  expect(copied.rows[1].surfaceId).toBe(`bed:${copied.beds[1].id}`);
  expect(rowPlants(copied.rows[1])[0].x).toBeCloseTo(bed.x + 20);
  const object = fixture.objects[0]; if (object.type !== "structure") throw new Error("fixture");
  const points = cropPlacementPoints(fixture, "Lettuce", object, null, "fill", "object:raised", 30);
  const planted = addCropPoints(fixture, "Lettuce", "Butterhead", points, "object:raised", 30);
  const moved = reconcileOwnedPlants(planted, { ...planted, rows: [...planted.rows, row], objects: [{ ...object, x: object.x + 40 }] });
  expect(moved.rows).toHaveLength(planted.rows.length + 1);
  expect(rowPlants(moved.rows[0])[0].x).toBeCloseTo(points[0].x + 40);
  expect(moved.rows.at(-1)).toEqual(row);
});

test("garden size, contextual planting, templates, save and 2D refresh work", async ({ context, page }, info) => {
  test.setTimeout(150_000);
  let saved = structuredClone(fixture), writes = 0;
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));
  await context.route("**/api/**", (route) => {
    const request = route.request(), path = new URL(request.url()).pathname;
    if (path === "/api/garden") { if (request.method() === "PUT") { saved = request.postDataJSON().plan; writes++; } return route.fulfill({ json: { ok: true, plan: saved } }); }
    return route.fulfill({ json: { ok: true, gardens: [{ id: "blenheim-garden", name: "Test", year: 2026 }], history: [], beds: [], items: [] } });
  });
  await page.goto("/3d?view=3d");
  const canvas = page.locator('[aria-label="Interactive 3D garden workspace"] canvas');
  await expect(canvas).toBeVisible();
  await page.getByRole("button", { name: "Garden size", exact: true }).click();
  await page.getByLabel("Garden width (m)").fill("12");
  await page.getByLabel("Garden depth (m)").fill("14");
  await page.getByRole("button", { name: "Apply garden size" }).click();
  await expect.poll(async () => (await readPlan(page)).canvasWidthCm).toBe(1200);
  expect(bedRectangle((await readPlan(page)).beds[0], await readPlan(page))).toEqual(bedRectangle(fixture.beds[0], fixture));
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect.poll(async () => gardenDimensions(await readPlan(page)).width).toBe(900);
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await page.getByRole("button", { name: "Plant a bed", exact: true }).click();
  await page.getByLabel("Planting bed").selectOption("object:raised");
  await page.getByRole("button", { name: "Apply seasonal layout", exact: true }).click();
  await expect.poll(async () => (await readPlan(page)).rows.flatMap(rowPlants).length).toBeGreaterThan(0);
  await page.locator('.garden-edit-inspector').getByLabel("Template name").fill("Timber 240");
  await page.getByRole("button", { name: "Save bed template" }).click();
  await page.getByRole("button", { name: "Edit key", exact: true }).click();
  await page.getByLabel("Garden edit key", { exact: true }).fill("isolated-test-key");
  await page.getByRole("button", { name: "Set key", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.locator(".garden-edit-status")).toContainText("Saved to cloud");
  expect(writes).toBe(1);
  await page.screenshot({ path: info.outputPath("garden-builder.png") });
  await page.reload();
  await expect(canvas).toBeVisible();
  await page.getByRole("button", { name: "Garden size", exact: true }).click();
  await expect(page.getByLabel("Garden width (m)")).toHaveValue("12");
  await page.screenshot({ path: info.outputPath("garden-size.png") });
  await page.getByRole("button", { name: "Close garden size" }).click();
  await page.goto("/");
  await expect(page.locator(".garden-canvas")).toHaveCSS("width", "1200px");
  await expect(page.locator(".garden-canvas")).toHaveCSS("height", "1400px");
  await page.screenshot({ path: info.outputPath("garden-builder-2d.png") });
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  expect(errors).toEqual([]);
});

test("drag planting, resize handles, fence drawing and multi-select work", async ({ context, page }, info) => {
  test.setTimeout(150_000);
  const errors: string[] = []; page.on("pageerror", (e) => errors.push(e.message));
  await context.route("**/api/**", (route) => route.fulfill({ json: { ok: true, plan: fixture, gardens: [], history: [] } }));
  await page.goto("/3d?view=3d");
  const canvas = page.locator('[aria-label="Interactive 3D garden workspace"] canvas');
  await expect(canvas).toBeVisible();
  await page.getByRole("button", { name: "Top", exact: true }).click();
  await expect(canvas).toHaveAttribute("data-camera", /projection/);
  const screen = async (x: number, y: number, height = 0) => {
    const value = JSON.parse((await canvas.getAttribute("data-camera"))!) as { projection: number[]; world: number[] };
    const camera = new THREE.PerspectiveCamera(); camera.projectionMatrix.fromArray(value.projection); camera.matrixWorld.fromArray(value.world); camera.matrixWorldInverse.copy(camera.matrixWorld).invert();
    const p = new THREE.Vector3(x / 100 - 4.5, height, y / 100 - 5.4).project(camera), b = (await canvas.boundingBox())!;
    return { x: b.x + (p.x + 1) * b.width / 2, y: b.y + (1 - p.y) * b.height / 2 };
  };
  const drag = async (a: { x: number; y: number }, b: { x: number; y: number }) => {
    await page.mouse.move(a.x, a.y); await page.mouse.down(); await page.mouse.move(b.x, b.y, { steps: 15 }); await page.mouse.up();
  };
  const collapse = async () => { for (const cls of [".garden-edit-palette", ".garden-edit-inspector"]) { const panel = page.locator(`${cls}[open]`); if (await panel.count()) await panel.locator("summary").click(); } };
  const object = fixture.objects[0]; if (object.type !== "structure") throw new Error("fixture");
  const soil = structureSurface(object);
  await page.getByRole("button", { name: "Fill patch", exact: true }).click();
  const palette = page.locator(".garden-edit-palette");
  await palette.getByRole("combobox", { name: "Crop", exact: true }).selectOption("Lettuce");
  await palette.getByLabel("Planting target").selectOption("object:raised");
  await collapse();
  const a = surfaceWorld(soil, { x: -85, y: -45 }), b = surfaceWorld(soil, { x: 85, y: 45 });
  await drag(await screen(a.x, a.y, soil.height), await screen(b.x, b.y, soil.height));
  await expect.poll(async () => (await readPlan(page)).rows.flatMap(rowPlants).length).toBeGreaterThan(5);
  const filled = await readPlan(page);
  expect(filled.rows.every((r) => r.surfaceId === "object:raised")).toBe(true);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.getByRole("button", { name: "Plant brush", exact: true }).click(); await collapse();
  await drag(await screen(a.x, a.y, soil.height), await screen(b.x, b.y, soil.height));
  await expect.poll(async () => (await readPlan(page)).rows.flatMap(rowPlants).length).toBeGreaterThan(1);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.getByRole("button", { name: "Add fence", exact: true }).click(); await collapse();
  await drag(await screen(400, 780), await screen(700, 780));
  await expect.poll(async () => (await readPlan(page)).objects.some((o) => o.type === "structure" && o.kind === "fence")).toBe(true);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.locator(".garden-build-options > summary").click();
  await page.getByText("Select several objects", { exact: true }).click();
  await page.locator(".garden-build-options").getByLabel("Salad bed", { exact: true }).check();
  await page.locator(".garden-build-options").getByLabel("Raised bed", { exact: true }).check();
  await page.getByRole("button", { name: "10 cm →", exact: true }).click();
  const moved = await readPlan(page);
  expect(bedRectangle(moved.beds[0], moved).x).toBeCloseTo(100);
  expect(moved.objects[0]).toMatchObject({ x: 560 });
  await page.getByRole("button", { name: "Clear selection", exact: true }).click();
  await page.locator(".garden-build-options > summary").click();
  await page.getByRole("button", { name: "Select", exact: true }).click();
  const center = await screen(550, 550, soil.height); await page.mouse.click(center.x, center.y);
  await expect(page.locator(".garden-edit-inspector")).toContainText("Raised bed");
  await page.getByRole("button", { name: "Resize", exact: true }).click(); await collapse();
  const handle = surfaceWorld({ ...soil, width: 240, depth: 160 }, { x: 120, y: 80 });
  const end = surfaceWorld(soil, { x: 140, y: 95 });
  await drag(await screen(handle.x, handle.y, soil.height), await screen(end.x, end.y, soil.height));
  await expect.poll(async () => ((await readPlan(page)).objects[0] as { widthCm: number }).widthCm).toBeGreaterThan(240);
  await page.screenshot({ path: info.outputPath("garden-building-tools.png") });
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  expect(errors).toEqual([]);
});
