import { expect, test } from "@playwright/test";

test("tomato model loads, rotates, adjusts and exports without garden writes", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  const gardenRequests: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (request) => {
    if (request.url().includes("/api/garden")) gardenRequests.push(request.url());
  });
  await page.goto("/3d-models/tomato");
  await expect(page.getByRole("link", { name: "3D garden", exact: true })).toBeVisible();
  const frame = await page.locator('iframe[title="Interactive tomato model"]').elementHandle().then((element) => element!.contentFrame());
  if (!frame) throw new Error("Model frame missing");
  await frame.waitForFunction(() => Boolean((window as unknown as { frameModel?: { ready: boolean } }).frameModel?.ready));
  await frame.locator("#spin").click();
  const canvas = frame.locator("canvas").first();
  await expect(canvas).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("tomato-model.png") });
  const before = await canvas.screenshot();
  await frame.locator("#t").focus();
  await page.keyboard.press("Home");
  await expect(frame.locator("#vt")).toHaveText("2 / 6");
  const sparse = await canvas.screenshot();
  expect(sparse.equals(before)).toBe(false);
  await frame.locator("#r").focus();
  await page.keyboard.press("Home");
  await expect(frame.locator("#vr")).toHaveText("0%");
  expect((await canvas.screenshot()).equals(sparse)).toBe(false);
  const bounds = await canvas.boundingBox();
  if (!bounds) throw new Error("Model canvas missing");
  const beforeOrbit = await canvas.screenshot();
  await page.mouse.move(bounds.x + bounds.width * .45, bounds.y + bounds.height * .5);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * .65, bounds.y + bounds.height * .55, { steps: 8 });
  await page.mouse.up();
  expect((await canvas.screenshot()).equals(beforeOrbit)).toBe(false);
  const download = page.waitForEvent("download");
  await frame.locator("#export").click();
  expect((await download).suggestedFilename()).toBe("tomato-refined.glb");
  await expect(frame.locator("#status")).toHaveText("GLB exported · dimensions in metres");
  const model = await page.request.get("/models/tomato/tomato-refined.glb");
  expect(model.ok()).toBe(true);
  const bytes = await model.body();
  expect(bytes.toString("ascii", 0, 4)).toBe("glTF");
  expect(bytes.readUInt32LE(4)).toBe(2);
  expect(bytes.readUInt32LE(8)).toBe(bytes.length);
  expect(bytes.length).toBeLessThan(25 * 1024 * 1024);
  const layout = await page.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth }));
  expect(layout.documentWidth).toBeLessThanOrEqual(layout.width);
  expect(errors).toEqual([]);
  expect(gardenRequests).toEqual([]);
  await testInfo.attach("diagnostics", { body: JSON.stringify({ layout, errors, gardenRequests, modelBytes: bytes.length }), contentType: "application/json" });
});
